---
services:
  pxt-arcade:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3232:3232"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- .:/usr/src/app
